# Generated by Django 5.1.11 on 2025-08-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Whether this topic is recommended for users'),
        ),
    ]
