# Generated by Django 5.1.11 on 2025-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_topic_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='supplementary_prompts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
